# Generated by Django 4.1 on 2022-08-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
    ]
