# Generated by Django 4.1 on 2022-08-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_list_contributors'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='listentry',
            order_with_respect_to='list',
        ),
    ]
