# Generated by Django 4.1 on 2022-08-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_listentry_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listentry',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='listentry',
            order_with_respect_to=None,
        ),
    ]
